package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// cmdOrgs regenerates wiki/institutions.md: papers grouped by author
// institution and by funding sponsor, so people can search by 機構名稱.
func cmdOrgs(_ []string) error {
	papers, err := loadPapers()
	if err != nil {
		return err
	}
	inst := map[string][]*Paper{}
	fund := map[string][]*Paper{}
	for _, p := range papers {
		for _, n := range p.Institutions {
			inst[n] = append(inst[n], p)
		}
		for _, n := range p.Funding {
			fund[n] = append(fund[n], p)
		}
	}

	sortKeys := func(m map[string][]*Paper) []string {
		keys := make([]string, 0, len(m))
		for k := range m {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			if len(m[keys[i]]) != len(m[keys[j]]) {
				return len(m[keys[i]]) > len(m[keys[j]])
			}
			return keys[i] < keys[j]
		})
		return keys
	}
	writeGroup := func(b *strings.Builder, m map[string][]*Paper, keys []string) {
		for _, k := range keys {
			list := m[k]
			sort.Slice(list, func(i, j int) bool { return list[i].ID < list[j].ID })
			fmt.Fprintf(b, "\n### %s (%d)\n\n", k, len(list))
			for _, p := range list {
				fmt.Fprintf(b, "- [%s](papers/%s.md)\n", p.Title, p.ID)
			}
		}
	}

	var b strings.Builder
	b.WriteString("# Institutions / 機構\n\n")
	fmt.Fprintf(&b, "Papers grouped by author institution (%d institutions) and funding sponsor (%d sponsors), for finding groups, companies, and potential collaborators. ", len(inst), len(fund))
	b.WriteString("Extracted from the papers' own affiliation and acknowledgment text; corrections welcome by PR.\n\nGenerated by `iswiki orgs` — do not edit by hand.\n\n## By institution\n")
	writeGroup(&b, inst, sortKeys(inst))
	b.WriteString("\n## By funding sponsor / 經費來源\n")
	writeGroup(&b, fund, sortKeys(fund))
	if err := os.WriteFile("wiki/institutions.md", []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wiki/institutions.md regenerated: %d institutions, %d sponsors\n", len(inst), len(fund))
	return nil
}
