package main

import (
	"fmt"
	"os"
	"strings"
)

const (
	beginMark = "<!-- PAPERS:BEGIN — generated by `iswiki readme`, do not edit by hand -->"
	endMark   = "<!-- PAPERS:END -->"
)

// cmdReadme regenerates the papers-with-code table between the README
// markers from data/papers/*.yaml.
func cmdReadme(_ []string) error {
	papers, err := loadPapers()
	if err != nil {
		return err
	}
	var withCode []*Paper
	for _, p := range papers {
		if p.Code.URL != "" {
			withCode = append(withCode, p)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\n_%d papers indexed · %d with open-source code — [add one](CONTRIBUTING.md)_\n\n", len(papers), len(withCode))
	if len(withCode) > 0 {
		b.WriteString("| Paper | Authors | Code | Wiki |\n|---|---|---|---|\n")
		for _, p := range withCode {
			authors := strings.Join(p.Authors, ", ")
			if len(p.Authors) > 3 {
				authors = strings.Join(p.Authors[:3], ", ") + " et al."
			}
			link := p.ISCAURL
			if p.DOI != "" {
				link = "https://doi.org/" + p.DOI
			}
			fmt.Fprintf(&b, "| [%s](%s) | %s | [code](%s) | [`%s`](wiki/papers/%s.md) |\n",
				p.Title, link, authors, p.Code.URL, p.ID, p.ID)
		}
	} else {
		b.WriteString("_No open-source entries yet — be the first: fill `code.url` in your paper's yaml and open a PR._\n")
	}

	readme, err := os.ReadFile("README.md")
	if err != nil {
		return err
	}
	src := string(readme)
	begin := strings.Index(src, beginMark)
	end := strings.Index(src, endMark)
	if begin < 0 || end < 0 || end < begin {
		return fmt.Errorf("README.md is missing the PAPERS:BEGIN/END markers")
	}
	out := src[:begin+len(beginMark)] + b.String() + src[end:]
	if err := os.WriteFile("README.md", []byte(out), 0o644); err != nil {
		return err
	}
	fmt.Printf("README.md table regenerated: %d papers, %d with code\n", len(papers), len(withCode))
	return nil
}
