package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	beginMark    = "<!-- PAPERS:BEGIN — generated by `iswiki readme`, do not edit by hand -->"
	endMark      = "<!-- PAPERS:END -->"
	catBeginMark = "<!-- CATEGORIES:BEGIN — generated by `iswiki readme`, do not edit by hand -->"
	catEndMark   = "<!-- CATEGORIES:END -->"
)

// cmdReadme regenerates the papers-with-code table between the README
// markers from data/papers/*.yaml.
func cmdReadme(_ []string) error {
	papers, err := loadPapers()
	if err != nil {
		return err
	}
	var withCode []*Paper
	catCount := map[string]int{}
	for _, p := range papers {
		if p.Code.URL != "" {
			withCode = append(withCode, p)
			catCount[p.Category]++
		}
	}
	// group rows by category — categories with the most code-linked papers
	// first (this can differ from the all-papers Browse-by-category order),
	// then by title within a category
	sort.SliceStable(withCode, func(i, j int) bool {
		a, b := withCode[i], withCode[j]
		if a.Category != b.Category {
			if catCount[a.Category] != catCount[b.Category] {
				return catCount[a.Category] > catCount[b.Category]
			}
			return a.Category < b.Category
		}
		return a.Title < b.Title
	})

	var b strings.Builder
	fmt.Fprintf(&b, "\n_%d papers indexed · %d with open-source code — [add one](CONTRIBUTING.md)_\n\n", len(papers), len(withCode))
	if len(withCode) > 0 {
		b.WriteString("| Paper | Authors | Organizations | Category | Code | Labels | Wiki |\n|---|---|---|---|---|---|---|\n")
		for _, p := range withCode {
			authors := strings.Join(p.Authors, ", ")
			if len(p.Authors) > 3 {
				authors = strings.Join(p.Authors[:3], ", ") + " et al."
			}
			link := p.ISCAURL
			if p.DOI != "" {
				link = "https://doi.org/" + p.DOI
			}
			category := ""
			if p.Category != "" {
				category = "`" + p.Category + "`"
			}
			labels := ""
			if len(p.Labels) > 0 {
				labels = "`" + strings.Join(p.Labels, "` `") + "`"
			}
			orgs := strings.Join(p.Institutions, ", ")
			if len(p.Institutions) > 3 {
				orgs = strings.Join(p.Institutions[:3], ", ") + " …"
			}
			fmt.Fprintf(&b, "| [%s](%s) | %s | %s | %s | %s | %s | [`%s`](wiki/papers/%s.md) |\n",
				p.Title, link, authors, orgs, category, codeCell(p), labels, p.ID, p.ID)
		}
	} else {
		b.WriteString("_No open-source entries yet — be the first: fill `code.url` in your paper's yaml and open a PR._\n")
	}

	readme, err := os.ReadFile("README.md")
	if err != nil {
		return err
	}
	src := string(readme)
	begin := strings.Index(src, beginMark)
	end := strings.Index(src, endMark)
	if begin < 0 || end < 0 || end < begin {
		return fmt.Errorf("README.md is missing the PAPERS:BEGIN/END markers")
	}
	src = src[:begin+len(beginMark)] + b.String() + src[end:]

	if cb, ce := strings.Index(src, catBeginMark), strings.Index(src, catEndMark); cb >= 0 && ce > cb {
		src = src[:cb+len(catBeginMark)] + categoriesBlock(papers) + src[ce:]
	}
	if err := os.WriteFile("README.md", []byte(src), 0o644); err != nil {
		return err
	}
	fmt.Printf("README.md table regenerated: %d papers, %d with code\n", len(papers), len(withCode))
	return nil
}

// codeDisplay turns a code URL into a short display name for the README
// table: owner/repo for known forges (HF-tagged for Hugging Face), the bare
// hostname for demo pages and everything else.
func codeDisplay(url string) string {
	u := strings.TrimPrefix(strings.TrimPrefix(url, "https://"), "http://")
	u = strings.TrimPrefix(u, "www.")
	u = strings.TrimSuffix(u, "/")
	host, path, _ := strings.Cut(u, "/")
	parts := strings.Split(path, "/")
	ownerRepo := func(i int) string {
		if len(parts) >= i+2 && parts[i] != "" && parts[i+1] != "" {
			return parts[i] + "/" + strings.TrimSuffix(parts[i+1], ".git")
		}
		return ""
	}
	switch host {
	case "github.com", "gitlab.com", "codeberg.org":
		if or := ownerRepo(0); or != "" {
			return or
		}
	case "huggingface.co":
		if len(parts) > 0 && (parts[0] == "datasets" || parts[0] == "spaces" || parts[0] == "collections") {
			if or := ownerRepo(1); or != "" {
				return or + " (HF)"
			}
		}
		if or := ownerRepo(0); or != "" {
			return or + " (HF)"
		}
	}
	return host
}

// codeCell renders the table's Code cell: display name plus the star count
// for GitHub repos when known.
func codeCell(p *Paper) string {
	name := codeDisplay(p.Code.URL)
	if p.Code.Stars > 0 && strings.HasPrefix(p.Code.URL, "https://github.com/") {
		name = fmt.Sprintf("%s ★%d", name, p.Code.Stars)
	}
	return fmt.Sprintf("[%s](%s)", name, p.Code.URL)
}

// categoriesBlock renders the per-category counts for the README from the
// canonical category field on each paper.
func categoriesBlock(papers []*Paper) string {
	counts := map[string]int{}
	for _, p := range papers {
		if p.Category != "" {
			counts[p.Category]++
		}
	}
	if len(counts) == 0 {
		return "\n_Categories not assigned yet._\n"
	}
	cats := make([]string, 0, len(counts))
	for c := range counts {
		cats = append(cats, c)
	}
	sort.Slice(cats, func(i, j int) bool {
		if counts[cats[i]] != counts[cats[j]] {
			return counts[cats[i]] > counts[cats[j]]
		}
		return cats[i] < cats[j]
	})
	var b strings.Builder
	b.WriteString("\n| Category | Papers |\n|---|---|\n")
	for _, c := range cats {
		fmt.Fprintf(&b, "| `%s` | %d |\n", c, counts[c])
	}
	b.WriteString("\nEvery paper page carries its `category` and `labels` in frontmatter — grep them, or browse [the topic index](wiki/index.md) and [institutions / 機構](wiki/institutions.md).\n")
	return b.String()
}
