package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// cmdToc regenerates wiki/index.md: papers grouped by primary topic.
func cmdToc(_ []string) error {
	papers, err := loadPapers()
	if err != nil {
		return err
	}
	groups := map[string][]*Paper{}
	for _, p := range papers {
		topic := "uncategorized"
		if len(p.Topics) > 0 {
			topic = p.Topics[0]
		}
		groups[topic] = append(groups[topic], p)
	}
	topics := make([]string, 0, len(groups))
	for t := range groups {
		topics = append(topics, t)
	}
	sort.Slice(topics, func(i, j int) bool {
		if len(groups[topics[i]]) != len(groups[topics[j]]) {
			return len(groups[topics[i]]) > len(groups[topics[j]])
		}
		return topics[i] < topics[j]
	})

	var b strings.Builder
	b.WriteString("# Wiki index\n\n")
	fmt.Fprintf(&b, "Compiled pages for all %d Interspeech 2026 papers, grouped by primary topic. ", len(papers))
	b.WriteString("Each page carries OKF frontmatter (`id`, `category`, `updated`, `confidence`, `source`).\n\nGenerated by `iswiki toc` — do not edit by hand.\n\n## Topics\n\n")
	for _, t := range topics {
		fmt.Fprintf(&b, "- [%s](#%s) (%d)\n", t, t, len(groups[t]))
	}
	for _, t := range topics {
		fmt.Fprintf(&b, "\n## %s\n\n", t)
		list := groups[t]
		sort.Slice(list, func(i, j int) bool { return list[i].Title < list[j].Title })
		for _, p := range list {
			code := ""
			if p.Code.URL != "" {
				code = fmt.Sprintf(" · [code](%s)", p.Code.URL)
			}
			fmt.Fprintf(&b, "- [%s](papers/%s.md)%s\n", p.Title, p.ID, code)
		}
	}
	if err := os.WriteFile("wiki/index.md", []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wiki/index.md regenerated: %d papers, %d topics\n", len(papers), len(topics))
	return nil
}
